name: flutter_taqwa_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_nav_bar: ^5.0.7
  flutter_svg: ^2.2.0
  provider: ^6.1.5
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  http: ^1.5.0-beta.2
  geolocator: ^11.1.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  get_storage: ^2.1.1
  hijri: ^3.0.0
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/play_store_512.png"

flutter:
  uses-material-design: true

  assets:
    - assets/esmaul_husna.json
    - assets/religious_information.json
    - assets/hadith.json
    - assets/images/
    - assets/svg/